kumuluzee:
  name: badge-service
  version: 0.1.0
  env:
    name: ${KUMULUZEE_ENV_NAME:dev}
  server:
    http:
      port: 8087
      address: "0.0.0.0"
  datasources:
    - jndi-name: jdbc/HikuDS
      connection-url: "jdbc:postgresql://localhost:5432/hikudb"
      username: "hikuuser"
      password: "hikupassword"
      pool:
        min-size: 1
        max-size: 3
  jwt-auth:
    issuer: ""
    jwks-uri: ""