CREATE SCHEMA IF NOT EXISTS badge_service;

ALTER DEFAULT PRIVILEGES IN SCHEMA badge_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA badge_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
